name: Snyk Security Scan

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main

jobs:
  snyk-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js (for React Native or hybrid apps)
        uses: actions/setup-node@v3
        with:
          node-version: '16' # or any required version

      - name: Install dependencies
        run: npm install

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        with:
          args: test --severity-threshold=medium
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Fail build if vulnerabilities found
        run: |
          snyk test --severity-threshold=medium
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
